"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

import type { DecisionSafetyResponse } from "@/domain/decision/decision.safety";
import { getUsageCount, incrementUsageCount } from "@/lib/client-usage-limits";
import { PRODUCT_PLATFORM_HEADER } from "@/lib/product-events";
import { trackProductEvent } from "@/lib/client-events";
import { readGenerationStream } from "@/lib/client-generation-stream";
import { GenerationLoadingState } from "@/components/generation-loading-state";
import { UpgradeProButton } from "@/components/upgrade-pro-button";

type DecisionGuidanceFormProps = {
  canAskUnlimited: boolean;
  askQuestionsPerDay: number | null;
  userKey: string;
};

export function DecisionGuidanceForm({
  canAskUnlimited,
  askQuestionsPerDay,
  userKey,
}: DecisionGuidanceFormProps) {
  const router = useRouter();
  const [question, setQuestion] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [safety, setSafety] = useState<DecisionSafetyResponse | null>(null);
  const [showUpgradePrompt, setShowUpgradePrompt] = useState(false);
  const [currentStage, setCurrentStage] = useState<string | null>(null);

  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();

    if (question.trim() === "") {
      setError("Please enter a question.");
      return;
    }

    if (canAskUnlimited === false && askQuestionsPerDay !== null) {
      const questionCount = getUsageCount("ask", userKey);

      if (questionCount >= askQuestionsPerDay) {
        setShowUpgradePrompt(true);
        setError("Unlock unlimited Guidance for your next decisions.");
        setSafety(null);
        void trackProductEvent(
          {
            event_name: "paywall_shown",
            feature: "ask",
            plan_type: "pro",
            upgrade_surface: "ask_usage_limit",
          },
          { onceKey: "paywall:ask:ask_usage_limit" },
        );
        return;
      }
    }

    setIsSubmitting(true);
    setError(null);
    setSafety(null);
    setShowUpgradePrompt(false);
    setCurrentStage(null);

    try {
      const response = await fetch("/api/generate-decision-guidance", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          [PRODUCT_PLATFORM_HEADER]: "web",
        },
        body: JSON.stringify({ question }),
      });

      if (response.headers.get("content-type")?.startsWith("text/event-stream")) {
        for await (const event of readGenerationStream(response)) {
          if (event.type === "stage") {
            setCurrentStage(event.label);
          } else if (event.type === "done") {
            if (canAskUnlimited === false && askQuestionsPerDay !== null) {
              incrementUsageCount("ask", userKey);
            }
            setQuestion("");
            const payload = event.payload as { conversationId?: string } | null;
            if (payload?.conversationId) {
              router.push(`/decision/${payload.conversationId}`);
            } else {
              router.refresh();
            }
            return;
          } else if (event.type === "error") {
            throw new Error(event.message);
          }
        }
      } else {
        const payload = (await response.json()) as {
          error?: string;
          safety?: DecisionSafetyResponse;
        };

        if (!response.ok) {
          throw new Error(payload.error || "Unable to get guidance.");
        }

        if (payload.safety !== undefined) {
          setSafety(payload.safety);
          return;
        }

        if (canAskUnlimited === false && askQuestionsPerDay !== null) {
          incrementUsageCount("ask", userKey);
        }

        setQuestion("");
        router.refresh();
      }
    } catch (error) {
      setError(error instanceof Error ? error.message : "Unable to get guidance.");
    } finally {
      setIsSubmitting(false);
      setCurrentStage(null);
    }
  }

  return (
    <form className="card card-feature stack" onSubmit={handleSubmit}>
      <div className="stack" style={{ gap: "0.35rem" }}>
        <p className="card-eyebrow">Ask a question</p>
        <h2 className="section-heading-serif">Ask one clear question</h2>
        <p className="card-subtitle">
          Keep it concrete. The sharper the decision, the sharper the guidance.
        </p>
      </div>

      <p className="muted" style={{ margin: 0, fontSize: "0.85rem" }}>
        Responses are generated by AI for entertainment and reflection — not
        medical, legal, or financial advice.
      </p>

      <label className="field">
        <span>Your question</span>
        <textarea
          name="question"
          placeholder="Should I move forward with this job offer, or wait?"
          rows={4}
          value={question}
          onChange={(event) => setQuestion(event.target.value)}
        />
      </label>

      <div className="page-actions">
        <button className="button" disabled={isSubmitting} style={{ width: "100%" }} type="submit">
          {isSubmitting ? "Working..." : "Get Guidance"}
        </button>
        {showUpgradePrompt ? (
          <UpgradeProButton
            className="button secondary"
            feature="ask"
            label="Unlock Pro"
            upgradeSurface="ask_usage_limit"
          />
        ) : null}
      </div>

      <div
        className="stack"
        style={{ gap: "0.5rem", maxWidth: "22rem", width: "100%" }}
      >
        {isSubmitting ? (
          <GenerationLoadingState
            compact
            stages={["Weighing your question", "Shaping your guidance"]}
            currentStage={currentStage ?? undefined}
          />
        ) : null}
      </div>

      {error === null ? null : (
        <p className="muted" style={{ margin: 0 }}>
          {error}
        </p>
      )}

      {safety === null ? null : (
        <div className="card card-state card-state--stale stack">
          <p className="card-eyebrow">Safety mode</p>
          <h2 className="card-title">{safety.headline}</h2>
          <p style={{ margin: 0, lineHeight: 1.7 }}>{safety.message}</p>
          <p style={{ margin: 0 }}>
            <strong>What to do now:</strong> {safety.urgent_action}
          </p>
          <div className="stack" style={{ gap: "0.35rem" }}>
            <p style={{ margin: 0 }}>
              <strong>Resources</strong>
            </p>
            {safety.resources.map((item) => (
              <p key={item} style={{ margin: 0 }}>
                - {item}
              </p>
            ))}
          </div>
        </div>
      )}
    </form>
  );
}
