defaults.url=https://sentry.io/
defaults.org=
defaults.project=
auth.token=

ios.bundle_IDENTIFIER=com.astrologerondemand.app
ios.scheme=AstrologerOnDemand

android.package=com.astrologerondemand.app

telemetry=false
