import { StyleSheet } from "react-native";

import { brandColors, brandRadii, brandSpacing } from "@/theme/brand";

export const appUi = StyleSheet.create({
  pageHero: {
    gap: 12,
  },
  pageHeroKickerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  pageHeroIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: brandColors.accentSoft,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: brandColors.border,
  },
  pageEyebrow: {
    color: brandColors.textSubtle,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  pageTitle: {
    color: brandColors.text,
    fontSize: 31,
    fontWeight: "700",
    letterSpacing: -0.7,
  },
  pageSubtitle: {
    color: brandColors.textMuted,
    fontSize: 15,
    lineHeight: 23,
  },
  metaText: {
    color: brandColors.textMuted,
    fontSize: 13,
    lineHeight: 19,
  },
  card: {
    gap: 12,
    borderRadius: brandRadii.card,
    backgroundColor: brandColors.surface,
    borderColor: brandColors.border,
    borderWidth: 1,
    padding: brandSpacing.card,
    shadowColor: "#171411",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 18,
    elevation: 2,
  },
  heroCard: {
    gap: 14,
    borderRadius: brandRadii.card,
    backgroundColor: brandColors.surfaceRaised,
    borderColor: brandColors.border,
    borderWidth: 1,
    padding: brandSpacing.card + 2,
    shadowColor: "#171411",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 22,
    elevation: 3,
  },
  featuredCard: {
    gap: 12,
    borderRadius: brandRadii.card,
    backgroundColor: brandColors.surfaceWarm,
    borderColor: brandColors.border,
    borderWidth: 1,
    padding: brandSpacing.card,
    shadowColor: "#171411",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 18,
    elevation: 2,
  },
  quietCard: {
    gap: 12,
    borderRadius: brandRadii.card,
    backgroundColor: brandColors.surfaceMuted,
    borderColor: brandColors.border,
    borderWidth: 1,
    padding: brandSpacing.card,
  },
  lockedCard: {
    backgroundColor: brandColors.lockedBackground,
    borderColor: brandColors.lockedBorder,
  },
  staleCard: {
    backgroundColor: brandColors.staleBackground,
    borderColor: brandColors.staleBorder,
  },
  sectionTitle: {
    color: brandColors.text,
    fontSize: 20,
    fontWeight: "700",
    letterSpacing: -0.25,
  },
  sectionLabel: {
    color: brandColors.textSubtle,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  supportingLabel: {
    color: brandColors.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  supportingText: {
    color: brandColors.textMuted,
    fontSize: 14,
    lineHeight: 21,
  },
  bodyText: {
    color: brandColors.text,
    fontSize: 16,
    lineHeight: 24,
  },
  leadText: {
    color: brandColors.text,
    fontSize: 19,
    lineHeight: 29,
    fontWeight: "600",
  },
  emphasisText: {
    color: brandColors.text,
    fontSize: 17,
    lineHeight: 27,
    fontWeight: "600",
  },
  pill: {
    alignSelf: "flex-start",
    borderRadius: brandRadii.pill,
    backgroundColor: brandColors.accentSoft,
    borderColor: brandColors.border,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  pillText: {
    color: brandColors.accent,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  primaryButton: {
    alignItems: "center",
    justifyContent: "center",
    borderRadius: brandRadii.control,
    backgroundColor: brandColors.accent,
    minHeight: 52,
    paddingHorizontal: 16,
  },
  secondaryButton: {
    alignItems: "center",
    justifyContent: "center",
    borderRadius: brandRadii.control,
    backgroundColor: brandColors.accentSoft,
    borderColor: brandColors.accent,
    borderWidth: 1,
    minHeight: 48,
    paddingHorizontal: 16,
  },
  primaryButtonText: {
    color: brandColors.accentContrast,
    fontSize: 16,
    fontWeight: "600",
  },
  secondaryButtonText: {
    color: brandColors.accent,
    fontSize: 15,
    fontWeight: "600",
    textAlign: "center",
  },
  textInput: {
    borderWidth: 1,
    borderColor: brandColors.border,
    borderRadius: brandRadii.control,
    backgroundColor: brandColors.surfaceRaised,
    color: brandColors.text,
    fontSize: 16,
    lineHeight: 22,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  emptyStateCard: {
    gap: 12,
    borderRadius: brandRadii.card,
    backgroundColor: brandColors.surface,
    borderColor: brandColors.border,
    borderWidth: 1,
    borderStyle: "dashed",
    padding: brandSpacing.card,
  },
  emptyStateList: {
    gap: 10,
    marginTop: 4,
  },
  emptyStateRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  emptyStateBullet: {
    width: 30,
    height: 30,
    borderRadius: 10,
    backgroundColor: brandColors.accentSoft,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  emptyStateBulletText: {
    color: brandColors.text,
    fontSize: 14,
    lineHeight: 20,
    flex: 1,
  },
  listBlock: {
    gap: 10,
  },
  listRow: {
    gap: 4,
    borderTopColor: brandColors.border,
    borderTopWidth: 1,
    paddingTop: 12,
  },
});
